api: yes
apiAddress: :9997

authMethod: internal
authInternalUsers:
  - user: any
    pass:
    ips: []
    permissions:
      - action: read
      - action: playback
      - action: api

webrtc: yes
webrtcAddress: :8889
webrtcAllowOrigins: ["*"]

paths: {}
