from __future__ import annotations

from datetime import datetime
from typing import Protocol, Self
from uuid import UUID

from arenax.domain.identity import User, UserRole
from arenax.domain.moment import Moment
from arenax.domain.session import Session


class UnitOfWork(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def get_session(self, session_id: UUID, *, lock: bool = False) -> Session | None: ...
    async def add_session(self, session: Session) -> None: ...
    async def save_session(self, session: Session) -> None: ...
    async def lock_spaces(self, space_ids: tuple[UUID, ...]) -> None: ...
    async def has_conflict(
        self, space_ids: tuple[UUID, ...], start: datetime, end: datetime, exclude: UUID | None = None
    ) -> bool: ...
    async def resolve_device_space(self, device_id: str) -> UUID | None: ...
    async def active_session_for_space(self, space_id: UUID, at: datetime) -> Session | None: ...
    async def physical_event_result(self, idempotency_key: str) -> tuple[bool, UUID | None] | None: ...
    async def record_physical_event(
        self, device_id: str, occurred_at: datetime, idempotency_key: str, accepted: bool,
        moment_id: UUID | None = None,
    ) -> None: ...
    async def add_moment(self, moment: Moment) -> None: ...
    async def add_timeline(self, session_id: UUID, kind: str, at: datetime, data: dict) -> None: ...
    async def add_outbox(self, kind: str, aggregate_id: UUID, payload: dict) -> None: ...
    async def commit(self) -> None: ...
    async def add_person(self, name: str) -> UUID: ...
    async def add_space(self, name: str) -> UUID: ...
    async def add_equipment(self, space_id: UUID, kind: str, external_id: str, configuration: dict) -> UUID: ...
    async def list_people(self) -> list[dict]: ...
    async def list_spaces(self) -> list[dict]: ...
    async def list_equipments(self, space_id: UUID | None = None) -> list[dict]: ...
    async def session_dossier(self, session_id: UUID) -> dict | None: ...
    async def list_sessions(
        self, start: datetime, end: datetime, space_id: UUID | None = None
    ) -> list[Session]: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def get_user_by_access(self, token_hash: str, now: datetime) -> User | None: ...
    async def add_user(
        self, name: str, email: str, password_hash: str, role: UserRole, now: datetime
    ) -> User: ...
    async def add_access(
        self, user_id: UUID, token_hash: str, now: datetime, expires_at: datetime,
        persistent: bool,
    ) -> None: ...
    async def revoke_access(self, token_hash: str, now: datetime) -> None: ...
    async def register_last_access(self, user_id: UUID, now: datetime) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...
