from __future__ import annotations

from datetime import datetime
from typing import Protocol, Self
from uuid import UUID

from arenax.domain.identity import User, UserRole, UserStatus
from arenax.domain.moment import Moment
from arenax.domain.payment import Payment
from arenax.domain.session import Session


class UnitOfWork(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb) -> None: ...
    async def get_session(self, session_id: UUID, *, lock: bool = False) -> Session | None: ...
    async def add_session(self, session: Session) -> None: ...
    async def save_session(self, session: Session) -> None: ...
    async def session_has_associated_events(self, session_id: UUID) -> bool: ...
    async def delete_session(self, session_id: UUID) -> None: ...
    async def lock_spaces(self, space_ids: tuple[UUID, ...]) -> None: ...
    async def spaces_are_active(self, space_ids: tuple[UUID, ...]) -> bool: ...
    async def has_conflict(
        self, space_ids: tuple[UUID, ...], start: datetime, end: datetime, exclude: UUID | None = None
    ) -> bool: ...
    async def resolve_device_space(self, device_id: str) -> UUID | None: ...
    async def active_session_for_space(self, space_id: UUID, at: datetime) -> Session | None: ...
    async def physical_event_result(self, idempotency_key: str) -> tuple[bool, UUID | None] | None: ...
    async def record_physical_event(
        self, device_id: str, occurred_at: datetime, idempotency_key: str, accepted: bool,
        moment_id: UUID | None = None,
    ) -> None: ...
    async def add_moment(self, moment: Moment) -> None: ...
    async def add_timeline(self, session_id: UUID, kind: str, at: datetime, data: dict) -> None: ...
    async def add_payment(self, payment: Payment) -> None: ...
    async def session_expected_amount(self, session_id: UUID, now: datetime) -> int: ...
    async def set_expected_amount_override(self, session_id: UUID, amount_cents: int) -> None: ...
    async def recalculate_session_expected_amount(
        self, session_id: UUID, now: datetime
    ) -> int: ...
    async def add_outbox(self, kind: str, aggregate_id: UUID, payload: dict) -> None: ...
    async def commit(self) -> None: ...
    async def add_client(
        self, name: str, client_type: str, document: str, postal_code: str,
        address: str, city: str, state: str, notes: str,
        phone: str, email: str, whatsapp: bool,
        administrative_status: str,
    ) -> UUID: ...
    async def add_space(
        self, name: str, minute_rate_cents: int, administrative_status: str
    ) -> UUID: ...
    async def get_space(self, space_id: UUID, *, lock: bool = False) -> dict | None: ...
    async def update_space(
        self, space_id: UUID, name: str, administrative_status: str, minute_rate_cents: int
    ) -> dict: ...
    async def space_has_dependencies(self, space_id: UUID) -> bool: ...
    async def delete_space(self, space_id: UUID) -> None: ...
    async def add_equipment(self, space_id: UUID, kind: str, external_id: str, configuration: dict) -> UUID: ...
    async def get_equipment(self, equipment_id: UUID, *, lock: bool = False) -> dict | None: ...
    async def update_equipment(
        self, equipment_id: UUID, space_id: UUID, kind: str, external_id: str, configuration: dict, administrative_status: str
    ) -> dict: ...
    async def delete_equipment(self, equipment_id: UUID) -> None: ...
    async def list_clients(self) -> list[dict]: ...
    async def get_client(self, client_id: UUID, *, lock: bool = False) -> dict | None: ...
    async def update_client(
        self, client_id: UUID, name: str, client_type: str, document: str,
        postal_code: str, address: str, city: str, state: str,
        notes: str, phone: str, email: str, whatsapp: bool,
        administrative_status: str,
    ) -> dict: ...
    async def client_has_sessions(self, client_id: UUID) -> bool: ...
    async def delete_client(self, client_id: UUID) -> None: ...
    async def list_spaces(self) -> list[dict]: ...
    async def list_equipments(self, space_id: UUID | None = None) -> list[dict]: ...
    async def session_dossier(self, session_id: UUID, now: datetime) -> dict | None: ...
    async def list_sessions(
        self, start: datetime, end: datetime, space_id: UUID | None = None
    ) -> list[Session]: ...
    async def list_in_progress_sessions(self) -> list[Session]: ...
    async def get_user_by_email(self, email: str) -> User | None: ...
    async def get_user_by_access(self, token_hash: str, now: datetime) -> User | None: ...
    async def add_user(
        self, name: str, email: str, password_hash: str, role: UserRole, now: datetime
    ) -> User: ...
    async def add_access(
        self, user_id: UUID, token_hash: str, now: datetime, expires_at: datetime,
        persistent: bool,
    ) -> None: ...
    async def revoke_access(self, token_hash: str, now: datetime) -> None: ...
    async def register_last_access(self, user_id: UUID, now: datetime) -> None: ...
    async def list_users(self) -> list[User]: ...
    async def get_user(self, user_id: UUID, *, lock: bool = False) -> User | None: ...
    async def update_user(self, user_id: UUID, role: UserRole, status: UserStatus, now: datetime) -> User: ...
    async def update_user_password(self, user_id: UUID, password_hash: str, now: datetime) -> None: ...
    async def revoke_user_accesses(self, user_id: UUID, now: datetime) -> None: ...
    async def count_active_owners(self) -> int: ...
    async def get_moment_replay_path(self, moment_id: UUID) -> str | None: ...
    async def get_moment_replay(self, moment_id: UUID, *, lock: bool = False) -> dict | None: ...
    async def get_operational_settings(self, *, lock: bool = False) -> dict: ...
    async def update_operational_settings(
        self,
        default_session_duration_minutes: int,
        replay_pre_duration_seconds: int,
        replay_post_duration_seconds: int,
        calculate_actual_time: bool,
        replay_retention_days: int | None,
        company: dict[str, str],
        now: datetime,
    ) -> dict: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...
